#server:
#  port: 9000
#
#spring:
#  application:
#    name: xdclass-video-service
#  zipkin:
#    base-url: http://47.119.158.204:9411/ #zipkin地址
#    discovery-client-enabled: false  #不用开启服务发现
#  sleuth:
#    sampler:
#      probability: 1.0 #采样百分比
#
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://rm-wz9bbdd4a97n2qhlpco.mysql.rds.aliyuncs.com:3306/cloud_video?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: linda
#    password: wpt!820823
#
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 47.119.158.204:8848
#    sentinel:
#      transport:
#        dashboard: 47.119.158.204:8858
#        port: 9998
#
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true