#server:
#  port: 8888
#
#spring:
#  application:
#    name: api-gateway
#  zipkin:
#    base-url: http://47.119.158.204:9411/ #zipkin地址
#    discovery-client-enabled: false  #不用开启服务发现
#  sleuth:
#    sampler:
#      probability: 1.0 #采样百分比
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 47.119.158.204:8848
#
#    gateway:
#      routes: #数组形式
#        - id: order-service  #路由唯一标识
#          #uri: http://127.0.0.1:8000  #想要转发到的地址
#
#          uri: lb://xdclass-order-service  #从nocas进行转发
#
#          order: 1 #优先级，数字越小优先级越高
#          predicates: #断言 配置哪个路径才转发
#            - Path=/order-server/**
#            #- Before=2020-09-11T01:01:01.000+08:00  # 在这个时间点之后不能访问
#            #- Query=source  #一定携带这个参数
#
#          filters: #过滤器，请求在传递过程中通过过滤器修改
#            - StripPrefix=1  #去掉第一层前缀
#
#      discovery:
#        locator:
#          enabled: true  #开启网关拉取nacos的服务
